# Generated by Django 5.1.6 on 2025-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageInteraction',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web App', 'Web App'), ('Mobile App', 'Mobile App'), ('AI/ML', 'AI/ML'), ('Game Development', 'Game Development'), ('DSA', 'DSA')], max_length=100),
        ),
    ]
