# Generated by Django 5.1.6 on 2025-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_pageinteraction_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
