# Generated by Django 5.1.6 on 2026-08-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_repo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Best Practices', 'Best Practices'), ('AI/ML', 'AI/ML'), ('Design', 'Design')], default='Engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hobbies/'),
        ),
    ]
