# Generated by Django 5.1.6 on 2026-08-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_blogpost_category_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('display_order', '-created_at', 'id')},
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='project',
            name='source_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
