# Generated by Django 5.1.6 on 2026-08-12 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_source_key_project_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_type',
            field=models.CharField(choices=[('Paper', 'Paper'), ('Proposal', 'Proposal'), ('Blog', 'Blog'), ('Research Note', 'Research Note')], default='Blog', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='research_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='research_area',
            field=models.CharField(default='General', max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Published', 'Published')], default='Completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
